package com.sts.finncub.usermanagement.request;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EmployeeRequest {
    // to add, update or get employee details
    private String employeeCode;
    private Long employeeId;
    private Long organizationId;
    private String status;
    private String title;
    private String firstName;
    private String middleName;
    private String lastName;
    private String maritalStatus;
    private String gender;
    private String dob;
    private String fatherName;
    private String motherName;
    private String spouseName;
    private String languageKnown;
    private String qualification;
    private String bloodGroup;
    private Long personalMob;
    private Long cugMob;
    private String personalEmail;
    private String officialEmail;
    private String landline;
    private String currentAdd;
    private String currentCity;
    private String currentState;
    private Long currentPincode;
    private String permanentAdd;
    private String permanentCity;
    private String permanentState;
    private Long permanentPincode;
    private String nationality;
    private String alternateCon;
    private String emergencyCon;
    private String employmentType;
    private String joiningDate;
    private String confirmationDate;
    private String promotionDate;
    private String relievingDate;
    private String aadharCard;
    private String pancardNo;
    private String pfNumber;
    private Long uanNo;
    private String drivingLicenceNo;
    private String passportNo;
    private String esicNo;
    private String bankName;
    private String ifscCode;
    private String bankMMID;
    private String bankVPA;
    private String bankAccType;
    private String bankAccNo;
    private String bankBranch;
    private String userId;
    private String profileImgPath;
    private String signImgPath;
    private Integer branchId;
    private String branchJoinDate;
    private Long departmentId;
    private Long departmentRoleId;
    private Long subDepartmentId;
    private String designationType;
    private Long designationId;
    private Long functionalTitleId;
    private Long organizationBand;
    private Long reportManagerId;
    private Long hrManagerId;
    private Long accManagerId;
    private String caste;
    private String religion;
    private String referenceType;
    private String referenceSource;
    private String referenceName;
    private String referenceId;
    private String relWithEmergPerson;
    private String resignDate;
    private String typeOfExit;
    private String grade;
    private String isSignatory;
    private String exitDate;
    private String isFnfClear;
    private String isVehicle;
    private String vehicleType;
    private String vehicleNumber;
    private List<String> bcId;
    private String aadharCardNumberOrig;
    private Integer baseLocation;
    private String isManager;
    private String isBranchManager;
    private String isBankValidated;
    private String bankValidationDate;
    private String bankResponse;
    private Long validationAttempts;
    private String isNameVerified;
    private String nameInBank;
}